---
kind: pipeline
type: docker
platform:
  os: linux
  arch: amd64
name: default

steps:
- name: app
  image: python:3.7-alpine
  commands:
    - pip install docker-compose
    - docker-compose run app sh -c "python manage.py wait_for_db && python manage.py test
    - flake8