---
kind: pipeline
type: docker
name: default

steps:
- name: app
  image: python:3.7-alpine
  commands:
    - pip install docker-compose
    - docker-compose run app sh -c "python manage.py wait_for_db"
    - docker-compose run app sh -c "python manage.py test"
    - docker-compose run app sh -c "flake8"